### ISSUE TITLE
Unhandled exception when processing the planet related to maxspeed parsing

### ISSUE THREAD

**Issue by xivk** [itinero/routing#106]
> Unhandled Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero.
> Parameter name: length
>    at System.String.Substring(Int32 startIndex, Int32 length)
>    at Itinero.IO.Osm.Normalizer.AttributeCollectionExtensions.NormalizeMaxspeed(IAttributeCollection tags, IAttributeCollection profileTags)
>    at Itinero.IO.Osm.Normalizer.DefaultTagNormalizer.Normalize(IAttributeCollection tags, IAttributeCollection profileTags, VehicleCache vehicleCache)
>    at Itinero.IO.Osm.Streams.RouterDbStreamTarget.<RegisterSource>b__17_0(OsmGeo osmGeo, Object param)
>    at OsmSharp.Streams.Filters.OsmStreamFilterDelegate.MoveNext(Boolean ignoreNodes, Boolean ignoreWays, Boolean ignoreRelations)
>    at OsmSharp.Streams.OsmStreamTarget.DoPull(Boolean ignoreNodes, Boolean ignoreWays, Boolean ignoreRelations)
>    at Itinero.IO.Osm.Streams.RouterDbStreamTarget.OnBeforePull()

**Comment by xivk** [comment]
Fixed.
