### ISSUE TITLE
"NullReferenceException" in RestrictionProcessor.SecondPass

### ISSUE THREAD

**Issue by ironromeo** [itinero/routing#46]
I am trying to LoadOsmData file europe-latest.osm.pbf (18GB) downloaded from here
http://download.geofabrik.de/europe.html 
I get an exception. Stacktrace below:
And my extra question:
I use nuget to reference Itinero (current version is 0.32.2.0). But I do not understand which platform version of referenced library (x63 or AnyCPU)? As far as I am concerned from reading issues it is important for big data files. 

Stack trace:
    System.NullReferenceException: Object reference not set to an instance of an object.
   at Itinero.IO.Osm.Restrictions.RestrictionProcessor.SecondPass(Way way)
   at Itinero.IO.Osm.Streams.RouterDbStreamTarget.AddWay(Way way)
   at OsmSharp.Streams.OsmStreamTarget.DoPull(Boolean ignoreNodes, Boolean ignoreWays, Boolean ignoreRelations)
   at Itinero.IO.Osm.Streams.RouterDbStreamTarget.OnBeforePull()
   at OsmSharp.Streams.OsmStreamTarget.Pull()
   at Itinero.IO.Osm.RouterDbExtensions.LoadOsmData(RouterDb db, IEnumerable`1 source, Boolean allCore, Boolean processRestrictions, IEnumerable`1 processors, Vehicle[] vehicles)
   at Itinero.IO.Osm.RouterDbExtensions.LoadOsmData(RouterDb db, Stream data, Boolean allCore, Vehicle[] vehicles)

**Comment by xivk** [comment]
Sorry about that, I've been aware of this issue for a few days now. This is because Itinero is trying to process the file in > 2 passes. 

I'm working right now on a fix, reducing memory usage during the process and speeding up the process so this can be done in just two passes. If you disable the restrictions processor things should work for now but obviously without turn restrictions.

Expect a fix somewhere in the next two days...

**Comment by xivk** [comment]
I fixed the problem but I have a few failing unitesttests so I need to first investigate why they are failing. Will be something for the first week of 2017, sorry!
