### ISSUE TITLE
Build RouterDB with more PBFs

### ISSUE THREAD

**Issue by alecava58** [itinero/routing#49]
I'm trying to build a RouterDB using the latest merge features with the following countries:
Spain
Portugal
Andorra
Canary islands

but during the [StreamProgress] information - Pass 2 - Way[2270000] @ 23789.8/s

There is an exception:

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Vertex 387263168 does not exist.
   at Itinero.Graphs.Geometric.GeometricGraph.GetVertex(UInt32 vertex)
   at Itinero.IO.Osm.Streams.RouterDbStreamTarget.TryGetValue(Int64 node, Coordinate& coordinate, Boolean& isCore)
   at Itinero.IO.Osm.Streams.RouterDbStreamTarget.AddWay(Way way)
   at OsmSharp.Streams.OsmStreamTarget.DoPull(Boolean ignoreNodes, Boolean ignoreWays, Boolean ignoreRelations)
   at Itinero.IO.Osm.Streams.RouterDbStreamTarget.OnBeforePull()
   at OsmSharp.Streams.OsmStreamTarget.Pull()

**Comment by xivk** [comment]
Having the same issue with europe, has to be related to the latest changes, something that slipped past all the tests...

Checking now...

**Comment by xivk** [comment]
This should fix this, I tested with spain and portugal combined. Sorry for the many issues lately. Hope this gets you going again.
