### ISSUE TITLE
Error contracting router db

### ISSUE THREAD

**Issue by alecava58** [itinero/routing#51]
I've created and succesfully conctracted Spain and Portugal routerdb.

I've succesfully create Italy routerdb but when I try to contract it I receive the following exception:

Unhandled Exception: System.ArgumentOutOfRangeException: Data payload too big.
Parameter name: data
   at Itinero.Graphs.Directed.DirectedDynamicGraph.AddEdge(UInt32 vertex1, UInt32 vertex2, UInt32 data)
   at Itinero.Algorithms.Contracted.EdgeBased.DirectedGraphBuilder`1.DoRun()
   at Itinero.Algorithms.AlgorithmBase.Run()
   at Itinero.RouterDbExtensions.AddContracted[T](RouterDb db, Profile profile, WeightHandler`1 weightHandler, Boolean forceEdgeBased)

Note that only for Italy (not for Spain) I have a SecondPassProcessor that add a custom tag to some ways.

**Comment by alecava58** [comment]
Wait Ben.
may be there was something wrong in my custom lua profile. I changed the profile and trying recontract the db.
Now is running. 
It takes time to finish but as soon as I have the result I'll let you know.

**Comment by alecava58** [comment]
It is ok. I changed the lua custom profile and the contraction has finished correctly.
